WEBthanh/Models/Photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBthanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int MaHinhAnh { get; set; }
        public string TenHinhAnh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NoiCapNhat { get; set; }
        public string TacGia { get; set; }
        public string MoTa { get; set; }
    }
}

WEBthanh/Controllers/DetailsThongTinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBthanh.Controllers
{
    public class DetailsThongTinController : Controller
    {
        // GET: DetailsThongTin
        public ActionResult DetailsThongTin()
        {
            return View();
        }
        public ActionResult MyWork()
        {
            return View();
        }
    }
}

WEBthanh/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;

namespace WEBthanh.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        [HttpGet]
        public ActionResult SignOut()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignOut(NGUOIDUNG kh)
        {
            if (ModelState.IsValid)
            {
                db.NGUOIDUNGs.Add(kh);
                db.SaveChanges();
            }
            return View();
        }



        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f["txtMatKhau"].ToString();

            NGUOIDUNG kh = db.NGUOIDUNGs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Đăng nhập thành công";
                Session["TaiKhoan"] = kh;
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ThongBao = "Sai tài khoản hoặc mật khẩu";
            return View();

        }

    }
}

WEBthanh/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;
using PagedList;
using PagedList.Mvc;

namespace WEBthanh.Controllers
{
    public class PhotosController : Controller
    {
        // GET: Photos
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        public PartialViewResult PhotosPartial(int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return PartialView(db.HinhAnhPhotos.ToList().ToPagedList( pageNumber,pageSize));
        }
        public ActionResult XemChiTiet(int MaHA)
        {
            HinhAnhPhoto photos = db.HinhAnhPhotos.SingleOrDefault(n => n.MaHA == MaHA);
            if (photos == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(photos);
        }

    }
}

WEBthanh/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;

namespace WEBthanh.Controllers
{
    public class PostsController : Controller
    {
        // GET: Posts
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        public ActionResult PostsPartial()
        {
            return View(db.BaiVietts.ToList());
        }
        public ActionResult TrichDoan()
        {
            return View(db.TrichhDoans.ToList());
        }
    }
}

WEBthanh/Controllers/SanPhamCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBthanh.Controllers
{
    public class SanPhamCaNhanController : Controller
    {
        // GET: SanPhamCaNhan
        public ActionResult SPCaNhan()
        {
            return View();
        }
    }
}

WEBthanh/Controllers/SecondHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBthanh.Controllers
{
    public class SecondHomeController : Controller
    {
        // GET: SecondHome
        public ActionResult SecondIndex()
        {
            return View();
        }
    }
}

WEBthanh/Controllers/TimKiemBaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;
using PagedList;
using PagedList.Mvc;

namespace WEBthanh.Controllers
{
    public class TimKiemBaiVietController : Controller
    {
        // GET: TimKiemBaiViet
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f,int? page)
        {
            string sTuKhoa = f["txtfindphotos"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<HinhAnhPhoto> lstPhotos = db.HinhAnhPhotos.Where(n => n.DiaDiem.Contains(sTuKhoa)).ToList();

            int pageSize = 6;
            int pageNumber = (page ?? 1);
            if (lstPhotos.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm cần tìm";
                return View(db.HinhAnhPhotos.ToList().ToPagedList(pageNumber,pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstPhotos.Count + "sản phẩm";
            return View(lstPhotos.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult KetQuaTimKiem(string sTuKhoa,int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<HinhAnhPhoto> lstPhotos = db.HinhAnhPhotos.Where(n => n.Anh.Contains(sTuKhoa)).ToList();

            int pageSize = 6;
            int pageNumber = (page ?? 1);
            if (lstPhotos.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm cần tìm";
                return View(db.HinhAnhPhotos.ToList().ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstPhotos.Count + "sản phẩm";
            return View(lstPhotos.ToPagedList(pageNumber, pageSize));
        }
    }
}

WEBthanh/Views/Layout/DetailsThongTin.cshtml
<!DOCTYPE html>

<html  lang="en" class="no-js">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A Collection of Page Transitions</title>
    <meta name="description" content="A Collection of Page Transitions with CSS Animations" />
    <meta name="keywords" content="page transition, css animation, website, effect, css3, jquery" />
    <meta name="author" content="Codrops" />

    <link href="~/Content/DetailsThongTin/css/animations.css" rel="stylesheet" />
    <link href="~/Content/DetailsThongTin/css/component.css" rel="stylesheet" />
    <link href="~/Content/DetailsThongTin/css/default.css" rel="stylesheet" />
    <link href="~/Content/DetailsThongTin/css/multilevelmenu.css" rel="stylesheet" />
    <script src="~/Content/DetailsThongTin/js/modernizr.custom.js"></script>


    <link href="~/Content/fontawesome-free-5.1.0-web/css/all.css" rel="stylesheet" />
    <style>
        .menunhanh {
            position: absolute;
            top: 100px;
            right: 0;
            z-index: 10;
        }

            .menunhanh li {
                list-style-type: none;
            }

                .menunhanh li a {
                    display: block;
                }
    </style>
</head>

<body>
    @RenderBody()
    <div class="menunhanh">
        <ul>
            <li>
                <a href="https://www.facebook.com/profile.php?id=100025080900338" target="_blank"  style="width:40px;height:40px"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li> <a href="https://www.instagram.com/BuiThanh99/" target="_blank" style="width:40px;height:40px"><i class="fab fa-instagram"></i></a></li>
            <li> <a href="https://www.youtube.com/channel/UClBBjR3pQ3LfRgdxoHYQpqQ?view_as=subscriber" target="_blank"  style="width:40px;height:40px"><i class="fab fa-youtube"></i></a></li>
            <li> <a href="https://twitter.com/BuiThan90017624" target="_blank"  style="width:40px;height:40px"></a><i class="fab fa-twitter"></i></li>
        </ul>
    </div>

    <div class="codrops-top clearfix">
        <a class="codrops-icon codrops-icon-prev" href="@Url.Action("SecondIndex","SecondHome")"><span>Trở về trang chủ</span></a>
        @*<span class="right"><a class="codrops-icon codrops-icon-drop" href="http://tympanus.net/codrops/?p=15001"><span>Back to the Codrops Article</span></a></span>*@
    </div>

    <div class="pt-triggers">
        <button id="iterateEffects" class="pt-touch-button">Next</button>
    </div><!-- /triggers -->

    <div id="pt-main" class="pt-perspective">
        <div class="pt-page pt-page-3"><h1><span>About</span><strong>My</strong> Work</h1>
        <a href="@Url.Action("MyWork","DetailsThongTin")" style="position: absolute;top: 350px;z-index: 2;padding: 35px;border:1px solid black;cursor: pointer;left: 44.5%;border-radius: 20px;color:black">Details</a>
        </div>
        <div class="pt-page pt-page-5"><h1><span>About</span><strong>MY</strong> SELF</h1></div>
        <div class="pt-page pt-page-6">
            <h1><span>About</span><strong>Life</strong> Around</h1>
        </div>
    </div>

    <div class="pt-message">
        <p>Your browser does not support CSS animations.</p>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/Content/DetailsThongTin/js/jquery.dlmenu.js"></script>
    <script src="~/Content/DetailsThongTin/js/pagetransitions.js"></script>
</body>
</html>

WEBthanh/Views/Layout/Photos.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Cinzel|Modern+Antiqua|Playfair+Display" rel="stylesheet">
    <link href="~/Content/Responseeeeeee.css" rel="stylesheet" />

    <style>
        #ToanTrang {
            position: relative;
        }

        #thanhmenu {
            position: absolute;
            top:0;
            left:0;
            width: 1350px;
            height: 50px;
            background-color: lightgray;
            position:fixed;
            z-index:100;
        }

            #thanhmenu .txtfind {
                margin-left: 450px;
                margin-top: 5px;
                border-radius: 5px;
                height: 30px;
            }

            #thanhmenu li {
                float: right;
                list-style-type: none;
                margin-right: 50px;
            }

                #thanhmenu li a {
                    display: inline;
                    text-decoration: none;
                    margin-left: 20px;
                    font-size: 18px;
                    color: dimgray;
                }
    </style>
</head>
<body>
    <div id="ToanTrang">
        <div id="thanhmenu">
            @using (Html.BeginForm("KetQuaTimKiem", "TimKiemBaiViet", FormMethod.Post))
        {
            @Html.TextBox("txtfindphotos", " ", htmlAttributes: new { @class = "txtfind", @placeholder = "Bạn muốn tìm gì?" })
    }

            <p style="font-size:25px;font-family: 'Modern Antiqua', cursive;
margin-left:80px;margin-top:-30px;text-shadow:2px 2px 2px;"><a style="text-decoration:none" href="@Url.Action("PhotosPartial","Photos")"> Photos & Videos</a></p>
            <ul>
                <li><a href="#HinhAnh" style="position:absolute;top:12px;right:400px;">Images</a></li>
                <li><a href="#" style="position:absolute;top:12px;right:300px;">Videos</a></li>
            </ul>
        </div>
        <div style="position:absolute;left:-10px;top:250px;transform:rotate(-90deg);font-size:25px;color:crimson;padding:5px;background-color:black;position:fixed;z-index:1000;opacity:0.8"><a href="@Url.Action("SecondIndex","SecondHome")">Home</a></div>


        <div id="backgr" style="background-color:black;opacity:0.7;width:1250px;position:absolute;left:50px;height:550px;top:60px;">
            <div style="background-color:white;height:580px;width:5px;margin-left:600px;transform:rotate(10deg);position:absolute;top:-5px;"></div>
        </div>
        <div id="img1" style="border:1px solid red;width:350px;height:500px;position:absolute;top:85px;left:150px;background-color:black">
            <a href="#HinhAnh" style="text-decoration:none;">
                <img src="~/HinhAnhFirstPhotos/24f3ef5f8cd5638b3ac4.jpg" style="width:350px;height:400px;" />
                <p style="text-align:center;font-family: 'Abril Fatface', cursive;font-size:30px;color:white;">Hình Ảnh</p>
            </a>
        </div>
        <div id="img2" style="border:1px solid red;width:350px;height:500px;position:absolute;top:85px;right:150px;background-color:black">
            <img src="~/HinhAnhFirstPhotos/schools-promotional-videos.jpg" style="width:350px;height:400px;" />
            <p style="text-align:center;font-family: 'Abril Fatface', cursive;font-size:30px;color:white">Videos</p>
        </div>

        <div id="HinhAnh" style="position:absolute;top:620px;">
            <p style="font-family: 'Cinzel', serif;
font-size:30px;margin-left:585px;">Hình Ảnh</p>
            @RenderBody()

        </div>

        <br />

        @*<div id="Videos" style="position:absolute;top:2220px;">
            <p style="font-family: 'Cinzel', serif;
font-size:30px;margin-left:20px;">Videos</p>
            @RenderSection("NoiDung", false)
        </div>*@



        @*<div id="Videos" style="position:absolute;top:620px;">
                    <p style="font-family: 'Cinzel', serif;
        font-size:30px;margin-left:20px;">Hình Ảnh</p>

                </div>*@

    </div>
</body> 
</html>

WEBthanh/Views/Layout/Posts.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/assets/css/main.css" rel="stylesheet" />
    <noscript><link href="~/assets/css/noscript.css" rel="stylesheet" /></noscript>

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Playfair+Display" rel="stylesheet">
    <link href="~/Content/Responseeeeeee.css" rel="stylesheet" />
   
    <style>
        .titlePost {
            background-color: black;
            border: 1px solid black;
            z-index: 10;
            position: absolute;
            top: 270px;
            left: 33.5%;
            opacity: 0.2;
            font-size: 30px;
            text-align: center;
        }

            .titlePost:hover {
                transform: scale(1.2,1.2);
                opacity: 0.9;
                border: 1px solid red;
                color: white;
                transition: 2s;
            }

        #thanhmenu {
            position: absolute;
            top: 0;
            width: 100%;
            height: 80px;
            z-index: 3;
            background-color: black;
            position: fixed;
            opacity: 0.7;
        }

            #thanhmenu .txtfind {
                width: 400px;
                float: right;
                margin-right: 10px;
                margin-top: 15px;
            }
            body{overflow-x:hidden}
    </style>


</head>
<body >

    <div id="thanhmenu">
        <a href="@Url.Action("SecondIndex","SecondHome")"><h style="float:left;margin-left:50px;color:white;font-size:32px;font-family: 'Abril Fatface', cursive;"><strong style="color:white">THANH</strong> KT</h> </a> <p style="margin-top:16px;float:left;margin-left:40px;color:white;font-size:15px;">The page of <b style="font-size:20px;color:white">Bui Thanh</b></p>
        @using (Html.BeginForm())
        {
            @Html.TextBox("txtfind", " ", htmlAttributes: new { @class = "txtfind", @placeholder = "Bạn muốn tìm gì?" })
        }
    </div>
    <div id="BackgrPosts">
        <img src="~/HinhAnhDetailsTT/HinhAnhPosts/pexels-photo-1209843.jpeg" style="z-index:-1" />
        <img src="~/HinhAnhDetailsTT/HinhAnhPosts/pexels-photo-533923.jpeg" style="z-index:1;position:absolute;top:800px;height:1945px;opacity:0.8" />
    </div>
    <!-- Nav -->


    <nav id="nav">
        <ul class="links">
            <li class="active"><a href="@Url.Action("PostsPartial","Posts")">Bài viết</a></li>
            <li><a href="@Url.Action("TrichDoan","Posts")">Trích đoạn</a></li>
            <li><a href="elements.html">Góp ý</a></li>
        </ul>
    </nav>



    <!-- Main -->
    <div id="main">

        <!-- Featured Post -->
        <div id="titlePosts">
            <article class="post featured">
                <header class="major">
                    <span class="date">April 25, 2018</span>
                    <h2>
                        <a href="#">
                            And this is a<br />
                            my posts
                        </a>
                    </h2>
                    <p>
                        Dưới đây là tất cả các chủ đề về bài viết từ kinh nghiệm cá nhân của bản thân mình đã trải qua. Nó sẽ giúp ích ít nhiều trong những trải nghiệm bạn sẽ gặp phải.<br />Chúc bạn thành công!
                    </p>
                </header>
                <a href="#" class="image main"><img src="images/pic01.jpg" alt="" /></a>
                <ul class="actions special">
                    <li><a href="#" class="button large">Full Story</a></li>
                </ul>
            </article>
        </div>

        <!-- Posts -->
            <section class="posts">
                <article>
                    <div id="column1">
                        @RenderBody()
                    </div>
                </article>
            </section>

    </div>


    <!-- Copyright -->
    <div id="copyright">
        <ul><li>Thanh KT</li><li>Design: <a href="@Url.Action("Index","Home")">Myself</a></li></ul>
    </div>

    </div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>


</body>
</html>

WEBthanh/Views/Layout/SecondNguoiDungLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/NewNguoiDungLayout/css/style.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playball|Playfair+Display|Rouge+Script" rel="stylesheet">

    <style>
        #tongquat {
            background-image: url('../../HinhAnh/Backgr/amazing-animal-beautiful-beautifull.jpg');
            position: absolute;
            top: 385px;
            width: 100%;
            left: 0;
            height: 380px;
            background-color: red rgba(0,0,0,0.75);
            opacity: 0.3;
            background-attachment: fixed;
            transition: 0.25s;
            z-index: -2;
        }

        .inner {
            text-align: center;
            padding: 120px;
            color: red;
            font-size: 20px;
        }
    </style>

</head>
<body>
    @RenderBody()
    <!-- Profile Image -->
    <div id="main-profile-image">
        <img src="~/HinhAnh/HinhAnhThongTin/38600807_270517987065801_5013379582179409920_n.jpg" style="opacity:0.75;"/>
    </div>

    <div class="wrapper">

        <!-- Header -->
        <header>
            <h1 class="text-center">
                The blog of <span style="font-family: 'Playball', cursive;color:#DEB887;text-shadow:1px 1px 3px;

">Bui Thanh</span>
            </h1>
        </header>


        <!-- Main content area -->
        <main>
            <article>
                <p class="text-center">Welcome to my blog, where I share about my knowledge, the books I'm reading, more beautiful photos,so on. I hope that you'll subcribe. <a href="@Url.Action("DangNhap","NguoiDung")" title="ZyPOP">Sign In</a>.<br /><br /> <i>This is my </i><b>Posts</b>   <a href="@Url.Action("PostsPartial","Posts")" title="ZyPOP">Read more</a>.</p>

                <p class="text-center"> <i>All my <b>photos</b> what I took </i><a href="@Url.Action("PhotosPartial","Photos")">See them</a> </p>


                <p class="text-center no-spacer"><a href="#" class="button button-large">Contact me</a><br /><i style="color:black;text-align:center;">nguyenhoang30041975@gmail.com</i></p>

            </article>

        </main>

        <div id="tongquat">
            <div class="inner">
                <div style="background:linear-gradient(to right,black,red);position: absolute;
    top: 0px;
    width: 100%;
    left: 0;
    height: 500px;opacity: 0.4"></div>
                <h2 style="color:white;margin-top:72px;">Cám ơn bạn đã ghé thăm trang</h2>

            </div>
        </div>

        <div class="social-icons">
            <a href="https://www.facebook.com/profile.php?id=100023228045492
"><i class="fa fa-facebook-square fa-3x"></i></a>
            <a href="#"><i class="fa fa-twitter-square fa-3x"></i></a>
            <a href="https://www.youtube.com/channel/UClBBjR3pQ3LfRgdxoHYQpqQ?view_as=subscriber"><i class="fa fa-youtube-square fa-3x"></i></a>
            <a href="https://www.instagram.com/"><i class="fa fa-instagram fa-3x"></i></a>
        </div>


        <!-- Footer -->
        <footer>
            <p style="color:darkgray">Thank you for watching ! <a href="@Url.Action("DetailsThongTin","DetailsThongTin")"><span style="color:crimson">About me</span></a>.</p>
        </footer>
    </div>


</body>
</html>

WEBthanh/Views/Layout/TrichDoan.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="~/assets/css/main.css" rel="stylesheet" />
    <noscript><link href="~/assets/css/noscript.css" rel="stylesheet" /></noscript>
    <link href="~/Content/Responseeee2.css" rel="stylesheet" />
    <style>
        .titlePost {
            background-color: black;
            border: 1px solid black;
            z-index: 10;
            position: absolute;
            top: 270px;
            left: 33.5%;
            opacity: 0.2;
            font-size: 30px;
            text-align: center;
        }

            .titlePost:hover {
                transform: scale(1.2,1.2);
                opacity: 0.9;
                border: 1px solid red;
                color: white;
                transition: 2s;
            }
    </style>

</head>
<body class="is-preload">

    @RenderBody()

    @*<!-- Wrapper -->
        <div id="wrapper" class="fade-in">

            <!-- Intro -->
            <div id="intro">
                <h1>
                    This is<br />
                    Massively
                </h1>
                @*<p>
                    A free, fully responsive HTML5 + CSS3 site template designed by <a href="https://twitter.com/ajlkn">@ajlkn</a> for <a href="https://html5up.net">HTML5 UP</a><br />
                    and released for free under the <a href="https://html5up.net/license">Creative Commons license</a>.
                </p>*@
    @* <ul class="actions">
                <li><a href="#header" class="button icon solo fa-arrow-down scrolly">Continue</a></li>
            </ul>
        </div>

        <!-- Header -->
        <header id="header">
            <a href="index.html" class="logo">Massively</a>
        </header>*@

    <!-- Nav -->
    <div class="titlePost"><p style="margin-top:47px;text-align:center;padding:50px;border:1px solid black;">"Cùng chia sẻ, cùng thành công"</p></div>

    <div id="backgr1" style="z-index:2;position:absolute;top:800px;">
            <img src="~/HinhAnhPosts/pexels-photo-1209843.jpeg" />
       
        <div class="clear"></div>
        <img src="~/HinhAnhPosts/pexels-photo-533923.jpeg" style="height:2580px" />
    </div>


         <ul class="links">
            <li class="active"><a href="index.html">Bài viết</a></li>
            <li><a href="@Url.Action("TrichDoan","Posts")">Trích đoạn</a></li>
            <li><a href="elements.html">Góp ý</a></li>
        </ul>
    <!-- Main -->
    <div id="main">

        <section class="posts">
            <article>
                <div id="column1">
                    @Html.Action("TrichDoan", "Posts")
                </div>
            </article>
        </section>



        @* <!-- Featured Post -->
        <article class="post featured">
            <header class="major">
                <span class="date">April 25, 2018</span>
                <h2>
                    <a href="#">
                        And this is a<br />
                        my posts
                    </a>
                </h2>
                <p>
                    Tại đây là những phần trích đoạn từ nhiều nguồn kiến thức khác nhau chắc chắn sẽ mang lại nhiều lợi ích cho bạn<br />Chúc bạn thành công!
                </p>
            </header>
            <a href="#" class="image main"><img src="images/pic01.jpg" alt="" /></a>
            <ul class="actions special">
                <li><a href="#" class="button large">Full Story</a></li>
            </ul>
        </article>
        *@
        <!-- Posts -->


    </div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>


</body>
</html>