WEBthanh/Controllers/ChiTietTrichDoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;

namespace WEBthanh.Controllers
{
    public class ChiTietTrichDoanController : Controller
    {
        // GET: ChiTietTrichDoan
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        public ViewResult XemChiTietTD(int MaTD=0)
        {
            TrichhDoan trichdoan = db.TrichhDoans.SingleOrDefault(n => n.MaTD == MaTD);
            if (trichdoan == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(trichdoan);
        }
    }
}

WEBthanh/Controllers/NguoiDungADController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;

namespace WEBthanh.Controllers
{
    public class NguoiDungADController : Controller
    {
        // GET: NguoiDungAD
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(NGUOIDUNGAD nguoidungad)
        {
            if (ModelState.IsValid)
            {
                db.NGUOIDUNGADs.Add(nguoidungad);
                db.SaveChanges();
                ViewBag.ThongBao = "Đăng ký thành công";
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f["txtMatKhau"].ToString();

            NGUOIDUNGAD nguoidungad = db.NGUOIDUNGADs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);

            if(nguoidungad != null)
            {
                Session["TaiKhoan"] = nguoidungad;
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.ThongBao = "Sai tài khoản hoặc mật khẩu";
            return View();
        }
    }
}

WEBthanh/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBthanh.Models;

namespace WEBthanh.Controllers
{
    public class PostsController : Controller
    {
        // GET: Posts
        WEBTHANHEntities2 db = new WEBTHANHEntities2();
        public ActionResult PostsPartial()
        {
            return View(db.BaiVietts.ToList());
        }
        public ActionResult TrichDoan()
        {
            return View(db.TrichhDoans.ToList());
        }
    }
}

WEBthanh/Views/Posts/PostsPartial.cshtml
@using WEBthanh.Models;
@model List<BaiViett>

<link href="~/assets/css/main.css" rel="stylesheet" />
@*<link href="~/Content/TrangChu.css" rel="stylesheet" />*@
<link href="~/Content/Responseeeeeee.css" rel="stylesheet" />
@{
    /**/

    ViewBag.Title = "Bài Viết";
    Layout = "~/Views/Layout/Posts.cshtml";
}
<div id="column1">
    @*@{ int i = 0;}*@
    @foreach (var item in Model)
    {

        <div id="ThongTin">

            <header>

                <h2>
                    <a href="#" style="text-align:center;margin-left:15px;">
                        @item.TenBV
                    </a>
                </h2>
                <span class="date">@item.NgayCapNhat</span>
            </header>
            <a href="#" class="image fit"><img src="@Url.Content("~/HinhAnhDetailsTT/HinhAnhPosts/Bài viết/" +item.Anh)" style="width:300px;height:200px;margin-left:90px;box-shadow: 4px 4px 4px;" /></a>


            <p style="text-align:center">@item.MoTa</p>
            <p style="text-align:center"><b>@item.Poster</b></p>
            <ul class="actions special">
                <li><a href="#" target="_blank" class="button">Read More</a></li>
            </ul>

        </div>
        @*if (i % 3 == 0)
            {
                <div style="clear:both"></div>
            }*@
    }
</div>
<div class="clear"></div>

WEBthanh/Views/Posts/TrichDoan.cshtml
@using WEBthanh.Models;
@model List<TrichhDoan>
<link href="~/assets/css/main.css" rel="stylesheet" />
@*<link href="~/Content/TrangChu.css" rel="stylesheet" />*@
<link href="~/Content/Responseeee2.css" rel="stylesheet" />

@{
    /**/

    ViewBag.Title = "Trích đoạn";
    Layout = "~/Views/Layout/Posts.cshtml";
}
<div style="margin-left:0px;width:200px;border:1px solid red;"><a href="@Url.Action("DangNhap","NguoiDungAD")">Quản lý trích đoạn</a></div>
<br />
@*<div style="width:1000px;margin-left:0px;">*@
    <div id="column1">
        @*@{ int i = 0;}*@
        @foreach (var item in Model)
        {
            //i++;
        <div id="ThongTin">

            <header>
                <div>@item.MaTD</div>
                <h2>
                    <a href="#" style="text-align:center;margin-left:15px;">
                        @item.TenTD
                    </a>
                </h2>
                <span class="date">@item.NgayCapNhat</span>
            </header>
            <a href="#" class="image fit"><img src="@Url.Content("~/HinhAnhTrichDoan/" +item.Anh)" style="width:300px;height:200px;margin-left:90px;box-shadow: 4px 4px 4px;" /></a>

            <p style="text-align:center"><b>@item.TacGia</b></p>
            <ul class="actions special">
                <li><a href="@Url.Action("XemChiTietTD","ChiTietTrichDoan",new { @MaTD=item.MaTD})" class="button">Read More</a></li>
            </ul>

        </div>
    @*if (i % 3 == 0)
    {
        <div style="clear:both"></div>
}*@
}
    </div>
    <div class="clear"></div>
@*</div>*@